name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
      - cron: '0 0 * * 6'     
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.13
        with:
          required-ros-distributions: rolling
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.3
        with:
          package-name: ray_tracing_plugin
          target-ros2-distro: rolling
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          